#!/usr/bin/env bash
# kjjjs
FILE="school"

# Check for existence
if [ -e "$FILE" ]; then
    echo "school file exists"

    # If the file exists, perform further checks
    if [ -s "$FILE" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    # Check if it is a regular file
    if [ -f "$FILE" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi

